TIME_LIVE: 0.5
LENGTH_LOCATION : 40
STD: 10
LENGTH_CENTER: 40
TIME_OUT: 1 # thời gian chờ để xác định hướng


TIME_SENT_COUNT: 10

TIME_SEND_TOTAL_COUNT: 30

MODE_HALF: False

USER_NAME: "samson"
PASSWORD: "Samson@123"

STREAM_SIZE: [960, 540]

WEB_HOST: "http://192.168.1.210:42034"
SERVER_NAME : "TC20241"
CONST_COMP_ID : 95
CONST_MEDIA_SERVER_HOST : "rtmp://192.168.1.210:1935"
WEB_HOST_POLYGON: "http://127.0.0.1:5000"

EXCEPTION_CAMERA: [313]  # huớng ngược với mặc định
EXCEPTION_CAMERA_DIR_X: [312]
